SMSApp/urls.py
from django.conf.urls import patterns, url
from SMSApp import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = patterns('',
    # GENERIC INDEX URLS
    url(r'^$', views.index, name='index'),
    url(r'^submitsms/$', views.smsconfirm, name='smsconfirm'),
    url(r'^blocknumber/$', views.blocknumber, name='blocknumber'),
    url(r'^blocknumber_confirm/$', views.blocknumber_confirm, name='blacklist'),

    #AUTH URLS
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signin_confirm/$', views.signin_confirm, name='signin_confirm'),
    url(r'^signout/$', views.signout_confirm, name='signout'),
    url(r'^register_confirm/$', views.register_confirm, name='register'),
    url(r'^register/$', views.register, name='register'),

    ####### USER ########
    # USER MANAGEMENT URLS
    url(r'^add_contact/$', views.add_contact, name='add_contact'),
    url(r'^edit_contact/$', views.edit_contact, name='edit_contact'),
    url(r'^delete_messages/$', views.delete_messages, name='delete_messages'),
    url(r'^update_password/$', views.update_password, name='update_password'),
    url(r'^update_profile/$', views.update_profile, name='update_profile'),

    # USER - PWRESET
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.reset_confirm, name='password_reset_confirm'),
    url(r'^reset/$', views.reset, name='reset'),
    url(r'^reset/success/$', views.reset_success, name='reset_success'),
    url(r'^reset/set/$', views.reset_sent, name='reset_sent'),

    # USER URLS
    url(r'^dashboard/(?P<username>\w+)/$', views.user_dashboard, name='user_dashboard'),

    url(r'^contacts/(?P<username>\w+)/$', views.user_contacts, name='user_contacts'),
    url(r'^contacts/(?P<username>\w+)/(?P<action>\w+)/$', views.user_contacts, name='user_contacts'),
    url(r'^contacts/(?P<username>\w+)/(?P<action>\w+)/(?P<search>\w+)/$', views.user_contacts, name='user_contacts'),
    url(r'^profile/(?P<username>\w+)/$', views.user_profile, name='user_profile'),
    url(r'^messages/(?P<username>\w+)/$', views.user_messages, name='user_messages'),
    url(r'^password/(?P<username>\w+)/$', views.user_password, name='user_password'),
    url(r'^billing/(?P<username>\w+)/$', views.user_billing, name='user_billing'),

)

SMSReminder/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()
if settings.DEBUG:
    import debug_toolbar

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'SMSReminder.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^SMSApp/', include('SMSApp.urls')),
    url(r'^admin/', include(admin.site.urls)),

)
if not settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )
else:
        urlpatterns += patterns('',
        (r'^__debug__/', include(debug_toolbar.urls)),
    )

SMSApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
import uuid
from uuidfield import UUIDField
# Create your models here.
class SMSUser(AbstractUser):
  number = models.CharField(max_length=12, unique=False, blank=False, null=False)
  network = models.CharField(max_length=15, unique=False, blank=False, null=False)

class Message(models.Model):
  user = models.ForeignKey('SMSUser', default = None, blank=True, null=True)
  uuid = UUIDField(auto=True)  
  number = models.CharField(max_length=12, unique=False, blank=False, null=False)
  network = models.CharField(max_length=20, unique=False, blank=False, null=False)
  text = models.CharField(max_length=160, unique=False, blank=False, null=False)
  time = models.DateTimeField(auto_now=False, db_index=True, blank=False, null=False)
  created = models.DateTimeField(auto_now=True)
  sent = models.BooleanField(default = False)
  cancelled = models.BooleanField(default = False)

#Used to ignore messages sent to number
class BlackList(models.Model):
  number = models.CharField(max_length=12, unique=True, blank=False, null=False)

class Friends(models.Model):
    user = models.ForeignKey('SMSUser', related_name='user')
    uuid = UUIDField(auto=True)
    first_name = models.CharField(max_length=25, blank=False, null=False)
    last_name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=12, unique=False, blank=False, null=False)
    network = models.CharField(max_length=20, blank=False, null=False)
    last_message = models.DateTimeField(blank=True, null=True)
    favorite = models.BooleanField(default = False)
    deleted = models.BooleanField(default = False)

SMSApp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from localflavor.us.forms import USPhoneNumberField
from dateutil.parser import *
from dateutil.tz import *
from time import mktime
from datetime import datetime

import time
from pytz import timezone
import pytz
from django.utils.timezone import utc
import parsedatetime.parsedatetime as pdt
User = get_user_model()


class ReminderForm(forms.Form):
    phone_number = USPhoneNumberField(required = True)
    date = forms.CharField(max_length=50, required = True)
    date2 = forms.CharField(max_length=50, required = True)
    message = forms.CharField(max_length=80, required = True)
    network = forms.CharField(max_length=80, required = True)

    def clean(self):
        time = self.cleaned_data.get('date')
        error_messages = []
        typeError = False
        valueError = False
        try:
            if parse(time):
                time = parse(time)
        except TypeError, ex:
            print "type error"
            typeError = True
            cal = pdt.Calendar()
            print cal.parse(time)
            time = datetime.fromtimestamp(mktime(cal.parse(time)[0]))

        except ValueError, exVal:
            print "value error"
            valueError = True
            cal = pdt.Calendar()
            print cal.parse(time)
            time = datetime.fromtimestamp(mktime(cal.parse(time)[0]))
        except AttributeError:
            raise ValidationError("Please enter a valid time format.")

        now = datetime.now()
        seconds = timestamp(time) - timestamp(now)
        print seconds
        if (typeError or valueError) and seconds < 0 :
            raise ValidationError("Please enter a valid time format.")

        return self.cleaned_data

def timestamp(date):
    try:
        return time.mktime(date.timetuple())
    except ValueError, exVal:
        raise ValidationError("Please enter a valid time format.")

class BlockForm(forms.Form):
    blacklist_phone_number = USPhoneNumberField()
    
class SigninForm(forms.Form):
    username = forms.CharField(max_length=20, required = True)
    password = forms.CharField(max_length=30, required = True)
    remember = forms.BooleanField(initial=False, required = False)
    
class RegisterForm(forms.Form):
    email = forms.EmailField(help_text='Please enter a valid email address', required = True)
    confirmemail = forms.EmailField(help_text='Please enter a valid email address', required = True)
    username = forms.CharField(max_length=40, required = True)
    password1 = forms.CharField(max_length=30, required = True)
    password2 = forms.CharField(max_length=30, required = True)
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    phone_number = USPhoneNumberField()
    network = forms.CharField(max_length=80, required = True)
    
    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        error_messages = []

        if User.objects.filter(email=email):
            #email already used
            error_messages.append("That email is already in use.")

        if User.objects.filter(username=username):
            error_messages.append("That username is already in use.")

        if (self.cleaned_data.get('email') != self.cleaned_data.get('confirmemail')):
            error_messages.append("Email addresses must match.")
            #raise ValidationError(
            #    "Email addresses must match."
            #)

        if not password2:
            #raise ValidationError("You must confirm your password")
            error_messages.append("You must confirm your password")
        if password1 != password2:
            error_messages.append("Your passwords do not match")
            #raise ValidationError("Your passwords do not match")
        if len(error_messages):
            raise ValidationError(error_messages)

        return self.cleaned_data

class ProfileForm(forms.Form):
    email = forms.EmailField(help_text='Please enter a valid email address', required = True)
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    phone_number = USPhoneNumberField()
    network = forms.CharField(max_length=80, required = True)
    
class ChangePasswordForm(forms.Form):
    password = forms.CharField(max_length=30, required = True)
    new_password = forms.CharField(max_length=30, required = True)
    confirm_password = forms.CharField(max_length=30, required = True)

class ResetPasswordForm(forms.Form):
    email = forms.EmailField(help_text='Please enter a valid email address', required = True)

class ResetNewPasswordForm(forms.Form):
    new_password1 = forms.CharField(max_length=30, required = True)
    new_password2 = forms.CharField(max_length=30, required = True)

NETWORK_CHOICES = (
    ('txt.att.net', 'AT&T'),
    ('messaging.sprintpcs.com', 'Sprint'),
    ('tmomail.net', 'T-Mobile'),
    ('vtext.com', 'Verizon'),

)

class AddContactForm(forms.Form):
    uuid = forms.CharField(max_length=50, required = False)
    first_name = forms.CharField(max_length=20, required = True)
    last_name = forms.CharField(max_length=20)
    phone_number = USPhoneNumberField(required = True)
    network = forms.CharField(max_length=80, required = True, widget=forms.Select(choices=NETWORK_CHOICES))
    favorite = forms.BooleanField(initial=False, required = False)

    def clean(self):
        first_name = self.cleaned_data.get('first_name')
        phone_number = self.cleaned_data.get('phone_number')
        network = self.cleaned_data.get('network')
        favorite = self.cleaned_data.get('favorite')
        error_messages = []



        if not first_name:
            error_messages.append("A first name is required")

        if not phone_number:
            error_messages.append("A phone number is required")

        if not network:
            error_messages.append("A network selection is required")

        if len(error_messages):
            raise ValidationError(error_messages)

        return self.cleaned_data

SMSApp/templates/SMSApp/user/user.html
{% extends "SMSApp/base/base.html" %}
<!-- MAIN MENU -->
{% block main_menu %}
    {% include "SMSApp/sections/menu.html" %}
{% endblock main_menu %}

<!-- USER MENU -->
{% block user_menu %}
   {% include "SMSApp/user/user_menu.html" %}
{% endblock user_menu %}

<!-- USER CONTROL CONTENT -->
{% block content %}
<div class="row">
  <!-- User Control Menu -->
  <div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
{#    <ul id="user_menu" class="nav nav-pills nav-stacked">#}
{#    <li class="{% ifequal pagetype "dashboard" %}active{% endifequal %}"><a href="{% url 'user_dashboard' user %}">Dashboard</a></li>#}
{#    <li class="{% ifequal pagetype "contacts" %}active{% endifequal %}"><a href="{% url 'user_contacts' user %}">Contacts</a></li>#}
{#      <li class="{% ifequal pagetype "profile" %}active{% endifequal %}"><a href="{% url 'user_profile' user %}">Profile</a></li>#}
{#      <li class="{% ifequal pagetype "messages" %}active{% endifequal %}"><a href="{% url 'user_messages' user %}">Messages</a></li>#}
{#      <li class="{% ifequal pagetype "password" %}active{% endifequal %}"><a href="{% url 'user_password' user %}">Change Password</a></li>#}
{#      <li class="{% ifequal pagetype "billing" %}active{% endifequal %}"><a href="{% url 'user_billing' user %}">Billing</a></li>#}
{#    </ul>#}
  </div>
</div>
<div class="row">
  <!-- User Control Content -->
  <!-- MESSAGES SECTION -->
  {% block message_section %}
    {% include "SMSApp/base/messages.html" %}
  {% endblock message_section %}
    {% if pagetype == "dashboard" %}
      {% include "SMSApp/user/user_dashboard.html" %}
    {% endif %}

    {% if pagetype == "profile" %}
      {% include "SMSApp/user/user_profile.html" %}
    {% endif %}
    
    {% if pagetype == "messages" %}
      {% include "SMSApp/user/user_messages.html" %}
    {% endif %}
    
    {% if pagetype == "password" %}
      {% include "SMSApp/user/user_password.html" %}
    {% endif %}
    
    {% if pagetype == "billing" %}
      {% include "SMSApp/user/user_billing.html" %}
    {% endif %}
    {% if pagetype == "contacts" %}
      {% include "SMSApp/user/user_contacts.html" %}
    {% endif %}
</div>

{% endblock content %}

SMSApp/templates/SMSApp/user/user_billing.html
Billing Page

SMSApp/templates/SMSApp/user/user_contacts.html
{% load staticfiles %}
{% load webdesign %}
<div id="contacts" class="col-md-12">
 {#      Tabler header controls#}
    <div class="panel panel-primary">
      <div class="panel-heading">
                  <div class="row text-center">
          <h4>Contacts</h4>
        </div>

      </div>
        <div class="panel-body panel-controls">
                        <div class="text-center col-xs-12 col-sm-4 col-md-4 col-lg-4">
                <div class="btn-group">
                  <button type="button" class="btn btn-default">
                      <a href="{% url 'user_contacts' user 'favorite'%}">Favs</a>

                  </button>
                  <button type="button" class="btn btn-default">
                      <a href="{% url 'user_contacts' user 'recent'%}">Most Recent</a>
                  </button>
                  <button type="button" class="btn btn-default">
                      <a href="{% url 'user_contacts' user 'az'%}">A-Z</a>
                  </button>
                  <button type="button" class="btn btn-default">
                      <a href="{% url 'user_contacts' user 'za'%}">Z-A</a>
                  </button>
                </div>
            </div>
            <div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
                <div class="input-group">
                  <input id='contact_search' type="text" class="form-control">
                  <span class="input-group-btn">
                    <button id="contact_search" class="btn btn-default" type="button"><a id="contact_search_url" href="{% url 'user_contacts' user 'search' %}">Search</a></button>
                  </span>
                </div><!-- /input-group -->
              </div><!-- /.col-lg-6 -->
            <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
             <button id="contactAdd" type="button" class="btn btn-info btn-block" data-container="body" data-toggle="popover" data-placement="bottom">Add</button>

            </div>
            </div>
        {#    Contact listings#}
      <div class="panel-body">
      {% if friends %}
          {%  for friend in friends %}
              <li class="contact-item" data-uuid='{{ friend.uuid }}' data-first='{{ friend.first_name }}' data-last='{{ friend.last_name }}' data-number='{{ friend.phone_number }}' data-network='{{ friend.network }}' data-favorite='{{ friend.favorite }}'>
                  <div class="col-sm-6 col-md-4 col-lg-3">
                      <div class="panel panel-info {% if friend.favorite == True %}favorite {% endif %}">
                          <div class="panel-heading ">
                              <div class="panel-title"  >{{ friend.first_name }} {{ friend.last_name }}
                              <a href="{% url 'user_contacts' user 'delete' friend.uuid%}">
                                  <span class="hoverhand glyphicon glyphicon-remove contact-icon"></span>
                              </a>
                              <span  data-container="body" data-toggle="popover" data-placement="bottom" class="hoverhand glyphicon glyphicon-edit contact-icon"></span>
                              {% if friend.favorite == True %}
                                   <span class="glyphicon glyphicon-star contact-icon"></span>
                              {% else %}
                                   <span class="glyphicon glyphicon-star-empty contact-icon"></span>
                              {% endif %}

                              </div>
                          </div>
                          <div class="panel-body">
                              <div >
                                  {{ friend.phone_number }}
                              </div>
                              <div >
                                  {% if friend.phone_number != None %}
                                    {{ friend.last_message }}
                                  {% else %}
                                  Never
                                  {% endif %}
                                  <span  data-container="body" data-toggle="popover" data-placement="bottom" class="hoverhand glyphicon glyphicon-envelope contact-icon"></span>
                              </div>
                          </div>
                      </div>
                  </div>
              </li>

          {% endfor %}
          {% else %}
          <p class="text-center"> Well this is embarrassing, you have no friends. Perhaps you should add one!</p>

      {% endif %}
      </div>
        </div>
    </div>

</div>
<div id="myModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="popoverContent hide">
  {% include "SMSApp/forms/add_contact_form.html" %}
</div>
<div class="popoverEditContent hide">
  {% include "SMSApp/forms/edit_contact_form.html" %}
</div>
<div class="popoverMessageContent hide">
  {% include "SMSApp/forms/message_contact_form.html" %}
</div>
<script>

    var popoverContent = $(".popoverContent").html();
    $(".popoverContent").remove();
    var popoverMessageContent = $(".popoverMessageContent").html();
    $(".popoverMessageContent").remove();
    var popovereditContent = $(".popoverEditContent").html();
    var contactSearchUrl = $('#contact_search_url').attr('href');
    $(".popoverEditContent").remove();
    $('#contactAdd').popover({
        html: true,
        content: function(){
            return popoverContent;
        }
    })
    $('.glyphicon-envelope').popover({
        html: true,
        content: function(e){
            return popoverMessageContent;
        }
    })
    $('.glyphicon-edit').popover({
        html: true,
        content: function(){
            return  popovereditContent;
        }
    })
    $('.glyphicon-envelope').on('shown.bs.popover', function(){
        dateHandler();

                var contactItem = $(this).parents('.contact-item'),
                phonenumber = contactItem.data("number"),
                network = contactItem.data("network"),
                popover = $('.popover-content');
            $('#id_phone_number', popover).val(phonenumber);
            $('#id_network', popover).val(network);
    });
    $('.glyphicon-edit').on('shown.bs.popover', function(){
                var contactItem = $(this).parents('.contact-item'),
                uuid = contactItem.data("uuid"),
                firstname = contactItem.data("first"),
                lastname = contactItem.data("last"),
                phonenumber = contactItem.data("number"),
                network = contactItem.data("network"),
                favorite = contactItem.data("favorite") == "True" ? true:false,
                popover = $('.popover-content');
            $('#id_uuid', popover).val(uuid);
            $('#id_first_name', popover).val(firstname);
            $('#id_last_name', popover).val(lastname);
            $('#id_phone_number', popover).val(phonenumber);
            $('#id_network', popover).val(network);
            $('#id_favorite', popover).prop("checked",favorite);

    });
    $('body').on('click', function (e) {
        $('[data-toggle="popover"]').each(function () {
            //the 'is' for buttons that trigger popups
            //the 'has' for icons within a button that triggers a popup
            if (!$(this).is(e.target) && $(this).has(e.target).length === 0 && $('.popover').has(e.target).length === 0) {
                $(this).popover('hide');
            }
        });
    });

    $('#contact_search').on('input', function (e){
        $('#contact_search_url').attr("href",contactSearchUrl + this.value );
    });

    var dateHandler = function(){
        var datepicker = $('.contactdatetimepicker')
        datepicker.datetimepicker();
          $("#remind_me_submit").click(function(e){
          var date = datepicker.data("DateTimePicker");

          if(date !== null){
            e.preventDefault();
            date = moment(date).zone('-0500').format('YYYY-MM-DD HH:mm');
            $("#id_date").val(date);
            $("#reminder_form").submit();
          }else{

          }

      })

      $("#id_date2").on("input", function(e){
          datepicker.data("DateTimePicker", null);
          console.log(e);
          $("#id_date").val(this.value)
      });

      datepicker.on("dp.show", function(e){
          console.log(e);
          // $("#id_date2").val("")
          // $("#id_date").val(this.value)
      });
      datepicker.on("dp.change", function(e){
          datepicker.data("DateTimePicker", e.date);
          console.log(e);
          // $("#id_date2").val("")
          // $("#id_date").val(this.value)
      });
    }
</script>

SMSApp/templates/SMSApp/user/user_dashboard.html
{% load staticfiles %}
{% load webdesign %}
<div id="dashboard" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 dashboard">
    <div class="panel panel-primary">
        {#      <div class="panel-heading">#}
        {#        <div class="row text-center">#}
        {#          <h4>Create Reminders</h4>#}
        {#        </div>#}
        {#      </div>#}
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    {% include "SMSApp/forms/user_reminder_form.html" %}
                </div>
            </div>
        </div>
    </div>

    <div class="row ">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 dashboard">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4 class="text-center">Recently Sent Messages</h4>
                </div>
                {% if sentmessages %}
                    <table class="table table-striped">

                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Number</th>
                            <th>Message</th>
                            <th>Time</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for message in sentmessages %}
                            <tr>
                                <td>{{ forloop.counter0 }} </td>
                                <td>{{ message.number }} </td>
                                <td> {{ message.text }} </td>
                                <td> {{ message.time }} CST</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <div class="panel-body">
                        There are no messages to display
                    </div>
                {% endif %}
            </div>

        </div>

        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 dashboard">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4 class="text-center">Upcoming Messages</h4>
                </div>
                {% if messagequeue %}
                    <table class="table table-striped">

                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Number</th>
                            <th>Message</th>
                            <th>Time</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for message in messagequeue %}
                            <tr>
                                <td>{{ forloop.counter0 }}</td>
                                <td>{{ message.number }}</td>
                                <td>{{ message.text }}</td>
                                <td>{{ message.time }} CST</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <div class="panel-body">
                        There are no messages to display
                    </div>
                {% endif %}
            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 dashboard">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4 class="text-center">Recent Contacts</h4>
                </div>
                <div class="panel-body">
                    {% if friends %}
                        {% for friend in friends %}
                            <li class="contact-item" data-uuid='{{ friend.uuid }}' data-first='{{ friend.first_name }}' data-last='{{ friend.last_name }}' data-number='{{ friend.phone_number }}' data-network='{{ friend.network }}' data-favorite='{{ friend.favorite }}'>
                                <div class="col-xs-12 col-sm-6 col-md-12 col-lg-12">
                                    <div class="panel panel-info {% if friend.favorite == True %}favorite {% endif %}">
                                        <div class="panel-heading ">
                                            <div class="panel-title">{{ friend.first_name }} {{ friend.last_name }} - {{ friend.last_messaged }}
                                                {% if friend.favorite == True %}
                                                    <span class="glyphicon glyphicon-star contact-icon"></span>
                                                {% else %}
                                                    <span class="glyphicon glyphicon-star-empty contact-icon"></span>
                                                {% endif %}
                                            </div>
                                        </div>
                                        <div class="panel-body">
                                            <div>
                                                {{ friend.phone_number }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    {% else %}
                        You haven't messaged any friends!
                    {% endif %}
                </div>
            </div>

        </div>
    </div>
</div>

SMSApp/templates/SMSApp/user/user_menu.html
{% block user_menu %}
  {% if user.id %}
{% comment %}{% if profile %}
          class="active"
      {% endif %}>{% endcomment %}
    <li>
      <a data-toggle="dropdown" role="button" href="{% url 'user_dashboard' user%}">{{ user }} <b class="caret"></b></a>
        <ul id="user_menu" role="menu" class="dropdown-menu">
            <li class="{% ifequal pagetype "dashboard" %}active{% endifequal %}"><a href="{% url 'user_dashboard' user %}">Dashboard</a></li>
            <li class="{% ifequal pagetype "contacts" %}active{% endifequal %}"><a href="{% url 'user_contacts' user %}">Contacts</a></li>
            <li class="{% ifequal pagetype "profile" %}active{% endifequal %}"><a href="{% url 'user_profile' user %}">Profile</a></li>
            <li class="{% ifequal pagetype "messages" %}active{% endifequal %}"><a href="{% url 'user_messages' user %}">Messages</a></li>
            <li class="{% ifequal pagetype "password" %}active{% endifequal %}"><a href="{% url 'user_password' user %}">Change Password</a></li>
        </ul>
    </li> 
    <li>
      <a href="{% url 'signout'%}">Logout</a>
    </li> 
  {% else %}
    <li>
      <a class="menulink" href="{% url 'signin' %}">Sign-in</a>
    </li>
    <li>
      <a href="{% url 'register'%}">Register</a>
    </li>
  {% endif %}
{% endblock user_menu %}

SMSApp/templates/SMSApp/user/user_password.html
<div id="profile_password" class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3 dashboard">
      <div class="panel panel-primary">
        <div class="panel-heading">
            <h4 class="text-center">Update password</h4>
        </div>
        <div class="panel-body">
            {% block profile_password_form %}
              {% include "SMSApp/forms/profile_password.html" %}
            {% endblock profile_password_form %}
        </div>
      </div>
</div>

SMSApp/templates/SMSApp/user/user_profile.html
{% load staticfiles %}
{% load webdesign %}
<div id="profile" class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3 dashboard">
      <div class="panel panel-primary">
        <div class="panel-heading">
            <h4 class="text-center">Update profile information</h4>
        </div>
        <div class="panel-body">
                {% block profile_form %}
                  {% include "SMSApp/forms/profile_form.html" %}
                {% endblock profile_form %}
        </div>
      </div>
</div>